export const dummyData = [
  {
    id: 1,
    name: "girl1",
    gender: "bride",
    born_year: "1985",
    religion: "hindu",
  },
  {
    id: 2,
    name: "girl2",
    gender: "bride",
    born_year: "1994",
    religion: "hindu",
  },
  {
    id: 3,
    name: "girl3",
    gender: "bride",
    born_year: "1980",
    religion: "muslim",
  },
  {
    id: 4,
    name: "girl4",
    gender: "bride",
    born_year: "1990",
    religion: "muslim",
  },
  {
    id: 5,
    name: "boy1",
    gender: "groom",
    born_year: "1980",
    religion: "hindu",
  },
  {
    id: 6,
    name: "boy2",
    gender: "groom",
    born_year: "1991",
    religion: "hindu",
  },
  {
    id: 7,
    name: "boy3",
    gender: "groom",
    born_year: "1992",
    religion: "hindu",
  },
  {
    id: 8,
    name: "boy4",
    gender: "groom",
    born_year: "1988",
    religion: "hindu",
  },
  {
    id: 9,
    name: "boy5",
    gender: "groom",
    born_year: "1978",
    religion: "hindu",
  },
  {
    id: 10,
    name: "boy6",
    gender: "groom",
    born_year: "1996",
    religion: "hindu",
  },
];
